name: Build & deploy

env:
  CI: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    
    - name: Install NPM packages
      run: npm ci
      working-directory: ./v2
    
    - name: Build project
      run: npm run build
      working-directory: ./v2
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./v2/build

    